labels:
  - help wanted
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Describe what your problem is! What is happening? What do you expect to
        happen instead? You can upload screenshots by dragging the screenshot
        file into the text box.
      placeholder: I was trying to do X... but Y kept happening...
